# According to https://packaging.python.org/en/latest/tutorials/packaging-projects/
[metadata]
name = FINALES2
version = 1.1.0
description = This package provides functionalities of the FINALES server.
long_description = file: README.md
license = MIT

[options]
package_dir =
    = src
packages = find:
install_requires =
    bcrypt==4.0.1
    click==8.1.7
    fastapi==0.104.1
    jose==1.0.0
    jsonschema==4.17.3
    jsonsubschema==0.0.7
    numpy==1.23.5
    passlib==1.7.4
    pre-commit==3.5.0
    pydantic==2.4.2
    pytest==7.4.3
    python-jose==3.3.0
    python-multipart==0.0.6
    requests==2.27.1
    setuptools==61.2.0
    sqlalchemy==2.0.23
    sqlalchemy_utils==0.41.1
    uvicorn==0.24.0.post1
python_requires = >=3.9

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    finales = FINALES2.cli.main:finales_cli
