# By ramirezfranciscof

version: "3"

services:
  finales:
    image: finales:v0.1
    ports:
      - 8888:8888
    volumes:
      - finales_data:/root/data
    environment:
      JUPYTER_TOKEN: "qwerty0123"
      SHELL: "/bin/bash"
      KEY_DATABASE_DUMP_ENDPOINT_ACCESS: "DEFAULT_KEY_PLACEHOLDER" # Placeholder key must be changed to open the endpoint

volumes:
  finales_data:
    external: true
