name: PullRequestToMainDevelopment
run-name: ${{ github.triggering_actor }} edited a pull-request to the main or development branch
on:
  pull_request:
    branches: # for an example see: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onevent_nametypes
      - main
      - development
jobs:
  testCode_ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - run: echo "This job was triggered by a ${{ github.event_name }} and it runs on a ${{ runner.os }}."
      - uses: actions/checkout@v3
      - name: Python ${{ matrix.python-version }} setup
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Installation of dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest black
          pip install -r requirements.txt
      - name: Linting with black
        uses: psf/black@stable  # for an example see: https://black.readthedocs.io/en/stable/integrations/github_actions.html
        with:
          src: "./src/FINALES2/test"
      - name: Run the tests
        run: |
          pytest -v ./src/FINALES2/test